### ISSUE TITLE
[REQ] fix license on GH

### ISSUE THREAD

**Issue by MarcoRavich** [victimofleisure/WaveShop#2]
Hi there, 1st of all thanks for your awesome (voluntary) work !

Since we've doxed this git in our [HyMPS project](https://github.com/forart/HyMPS) (under [Editors](https://github.com/forart/HyMPS/blob/main/Aeditors.md) - [Generic](https://github.com/forart/HyMPS/blob/main/Aeditors.md#generic-) section), can you please fix licensing terms for it ?

Our "problem" is that the relative license badge isn't generated correctly:

![](https://flat.badgen.net/github/license/victimofleisure/WaveShop/)
(generate url: https://flat.badgen.net/github/license/victimofleisure/WaveShop/)

This could be easily fixed by choosing a "correct" license file through the GH's wizard.

Although it may sounds like a minor aspect, this may help other devs to understand how reuse your code in other open projects and vice-versa that's a determining factor for the success and longevity of your project.

Last but not least, let us know how - in your opinion - we could improve our categorizations and links to resources in order to favor collaboration (and therefore evolution) between developers of listed projects.

Thanks in advance.

**Comment by victimofleisure** [comment]
The missing license is now fixed. Thanks for bringing that issue to my attention.

**Comment by MarcoRavich** [comment]
First of all, thanks for the timely fix!

As you can see (above too) the badge is now generated correctly.

Thanks again and, if you like/need, let us know (by replying to [our discussions](https://github.com/forart/HyMPS/discussions)) how we can support listed projects.

Last but not least, Happy New Year !

**Comment by victimofleisure** [comment]
Thank you for your reply. But when I look at the [Generic](https://github.com/forart/HyMPS/blob/main/Aeditors.md#generic) page WaveShop still shows no license. Why is that? Happy New Year.

**Comment by victimofleisure** [comment]
Here's a screen shot:
![WaveShop license screenshot](https://user-images.githubusercontent.com/5056038/210346626-c3c5eaa7-2236-478d-a751-69a36747c5c0.png)

**Comment by MarcoRavich** [comment]
> Thank you for your reply. But when I look at the [Generic](https://github.com/forart/HyMPS/blob/main/Aeditors.md#generic) page WaveShop still shows no license. Why is that? Happy New Year.
>
We do use this string in our page: https://flat.badgen.net/github/license/victimofleisure/WaveShop/?label=

Which generates this badge: ![](https://flat.badgen.net/github/license/victimofleisure/WaveShop/?label=)

So, it's probably a caching problem.

Anyway it should correctly showed in few ours...

Thanks again and let us know whatever you need from HyMPS.
